export const LOGIN = "LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const MEDIA_URL = "MEDIA_URL"
export const MEDIA_URL_SUCCESS = "MEDIA_URL_SUCCESS"
export const MEDIA_URL_FAIL = "MEDIA_URL_FAIL"

export const GET_QUOTE_DATA = "GET_QUOTE_DATA"
export const GET_QUOTE_DATA_SUCCESS = "GET_QUOTE_DATA_SUCCESS"
export const GET_QUOTE_DATA_FAIL = "GET_QUOTE_DATA_FAIL"

export const CREATE_QUOTE_DATA = "CREATE_QUOTE_DATA"
export const CREATE_QUOTE_DATA_SUCCESS = "CREATE_QUOTE_DATA_SUCCESS"
export const CREATE_QUOTE_DATA_FAIL = "CREATE_QUOTE_DATA_FAIL"

